name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: '5.10'

    - name: Build and test
      run: |
        cd /Users/melikesultancan/Desktop/ios/MySwift/ToDo/ToDo.xcodeproj
        swift build
        swift test
